### ISSUE TITLE
Support OCR processing in EU

### ISSUE THREAD

**Issue by yonatankatz** [googleapis/java-vision#25]
Hi,
The Vision API has the option to process the OCR in a certain loction (e.g. EU.)
This API is not supported in the java SDK.

Can you please add support for this capability?

**Comment by olavloite** [comment]
Hi @yonatankatz ,

Just to be sure I understand you correctly: Do you mean the `parent` field of for example this request: https://cloud.google.com/vision/docs/reference/rpc/google.cloud.vision.v1p4beta1#asyncbatchannotatefilesrequest

**Comment by yonatankatz** [comment]
@olavloite yes, but more specifically the location.
Assuming I have the key.json, you don't need the project id. But the location is interesting for GDPR issues.

**Comment by olavloite** [comment]
I understand that you would normally not need to specify the project if you already have the json key file, but the `parent` field is the field that you should use to specify the location where the processing should take place. In Java code you can use that field like this:

```java
    ImageAnnotatorClient client = ImageAnnotatorClient.create();
    client.batchAnnotateImages(
        BatchAnnotateImagesRequest.newBuilder()
            .setParent("projects/my-project/locations/eu")
            .addAllRequests(Arrays.asList(AnnotateImageRequest.getDefaultInstance()))
            .build());
```

(In a real application, the list of `AnnotateImageRequest`s should contain real requests, and not just a default request instance.)

**Comment by yonatankatz** [comment]
OK, thanks! i didn't see this API.
