### ISSUE TITLE
NoSuchMethodError when updating google-cloud-vision 1.103.2 -> 1.103.3/1.103.5

### ISSUE THREAD

**Issue by qeepcologne** [googleapis/java-vision#550]
when updating google-cloud-vision dependency from  1.103.2 to 1.103.3
i got the following error (on startup of webapp, no error on compilation):

`16.06.21 12:39:49  WARN [ort.AbstractApplicationContext: 591] Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'faceDetectorGoogle': Invocation of init method failed; nested exception is java.lang.NoSuchMethodError: 'com.google.api.gax.rpc.StubSettings$Builder com.google.cloud.vision.v1.stub.ImageAnnotatorStubSettings$Builder.setMtlsEndpoint(java.lang.String)' (main)
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'faceDetectorGoogle': Invocation of init method failed; nested exception is java.lang.NoSuchMethodError: 'com.google.api.gax.rpc.StubSettings$Builder com.google.cloud.vision.v1.stub.ImageAnnotatorStubSettings$Builder.setMtlsEndpoint(java.lang.String)'
`

code fragment causing the error is:
```
    @Value("${payment.google.publisher.credfile}")
    private String credFile;

    private final String[] scope = {"https://www.googleapis.com/auth/cloud-platform", "https://www.googleapis.com/auth/cloud-vision"};

    private ImageAnnotatorClient client;

    @PostConstruct
    public void init() {
        try {
            client = ImageAnnotatorClient.create(ImageAnnotatorSettings.newBuilder()
                    .setCredentialsProvider(FixedCredentialsProvider.create(
                            ServiceAccountCredentials.fromStream(new FileInputStream(credFile)).createScoped(scope))).build());
        } catch (IOException ex) {
            throw new UncheckedIOException(ex);
        }
    }
```

**Comment by munkhuushmgl** [comment]
@qeepcologne ARe you sure 1.103.5 version exist in this repo?

**Comment by munkhuushmgl** [comment]
@chingor13 Can u answer this question?

**Comment by qeepcologne** [comment]
https://mvnrepository.com/artifact/com.google.cloud/google-cloud-vision

**Comment by qeepcologne** [comment]
issue is not happening anymore with 1.103.6
