### ISSUE TITLE
Integration test failing consistently

### ISSUE THREAD

**Issue by chingor13** [googleapis/java-vision#57]
Example: https://source.cloud.google.com/results/invocations/069190be-447a-4a0d-99b1-a2271c6c27d2

**Comment by nnegrey** [comment]
I'd guess the model is returning some different results based on the call. But also looks like there are some duplicate tests that can be deleted. 

Like these 4 tests are a pair of duplicates with different inputs. 
https://github.com/googleapis/java-vision/blob/988c5db5cc1c070ef5dad872965690ad96dbd9d6/google-cloud-vision/src/test/java/com/google/cloud/vision/it/ITSystemTest.java#L396-L447

So I'd suggest taking the less flaky input result from the ML model
