### ISSUE TITLE
Ambiguity in the response received in OCR requests to Cloud Vision through Java library

### ISSUE THREAD

**Issue by manishbansal006** [googleapis/java-vision#61]
Hi team,

We are using "**spring-cloud-gcp-starter-vision:1.2.1.RELEASE**" to integrate the google vision API within our SpringBoot service.

Within this, we are passing publically accessible image URI's for OCR to be performed.

Method used: **ImageAnnotatorClient-> batchAnnotateImages(requests)**
Modes used: TEXT_DETECTION and DOCUMENT_TEXT_DETECTION

Here an example of images being sent:

1. https://previews.123rf.com/images/gow27/gow271511/gow27151100054/49180481-statistic-math-law-theory-and-mathematical-formula-equation-doodle-handwriting-icon-with-graph-chart.jpg

2. https://media.cheggcdn.com/media/7de/7de42600-8aef-426f-90fe-3bb0a761d497/mathsEquationImage.png

Above images are the same and are publically accessible.

But when we perform the load test on these on these 2 images one at a time then following is observed:

- More than 60% of the requests fail with the error: "We can not access the URL currently. Please download the content and pass it in." with image:  https://media.cheggcdn.com/media/7de/7de42600-8aef-426f-90fe-3bb0a761d497/mathsEquationImage.png

- No or zero errors are observed with the image: https://previews.123rf.com/images/gow27/gow271511/gow27151100054/49180481-statistic-math-law-theory-and-mathematical-formula-equation-doodle-handwriting-icon-with-graph-chart.jpg

Note: **media.cheggcdn.com** in 2nd image is self-hosted CloudFront on AWS while **previews.123rf.com** in 1st image is some other publically accessible image, we used 1st image and uploaded manually to our S3 bucket and now trying to access it via CloudFront (2nd image)

Earlier we were using **google-api-services-vision**  to perform OCR and were getting the same error reported under https://github.com/googleapis/google-cloud-java/issues/3525, hence we decided to use and upgrade to "**spring-cloud-gcp-starter-vision:1.2.1.RELEASE**" as an action item still we getting the same errors.

**Question: Why we are facing such a high number of errors when we run load test for CloudFront image URI? (limits for CloudFront by default is: 100,000 req per second)**

**Comment by morgandu** [comment]
Hi,

Thanks for opening the issue. Here is some explanation for the experienced issue, also with suggested solutions.

https://github.com/googleapis/nodejs-vision/issues/270#issuecomment-481064953

Closing this issue due to its age, feel free to reopen it if still experience the issue after trying out the suggested solutions.
